// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	entity "github.com/eafajri/hr-service.git/module/employee/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// AuditLogRepository is an autogenerated mock type for the AuditLogRepository type
type AuditLogRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: log, payload
func (_m *AuditLogRepository) Create(log entity.AuditLog, payload interface{}) error {
	ret := _m.Called(log, payload)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.AuditLog, interface{}) error); ok {
		r0 = rf(log, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuditLogRepository creates a new instance of AuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditLogRepository {
	mock := &AuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
